### ISSUE TITLE
A route named "Redirect" has been added as a child of a route with the same name. Route names must be unique and a nested route cannot use the same name as an ancestor.     at checkSameNameAsAncestor (vue-router.js?v=f6bbb98c:1210:13)     at addRoute (vue-router.js?v=f6bbb98c:1000:13)     at addRoute (vue-router.js?v=f6bbb98c:1011:11)     at vue-router.js?v=f6bbb98c:1115:29     at Array.forEach (<anonymous>)     at createRouterMatcher (vue-router.js?v=f6bbb98c:1115:10)     at createRouter (vue-router.js?v=f6bbb98c:2180:19)     at index.ts:7:16

### ISSUE THREAD

**Issue by PeterFangXiaoLin** [yudaocode/yudao-ui-admin-vue3#110]
```text
A route named "Redirect" has been added as a child of a route with the same name. Route names must be unique and a nested route cannot use the same name as an ancestor.
    at checkSameNameAsAncestor (vue-router.js?v=f6bbb98c:1210:13)
    at addRoute (vue-router.js?v=f6bbb98c:1000:13)
    at addRoute (vue-router.js?v=f6bbb98c:1011:11)
    at vue-router.js?v=f6bbb98c:1115:29
    at Array.forEach (<anonymous>)
    at createRouterMatcher (vue-router.js?v=f6bbb98c:1115:10)
    at createRouter (vue-router.js?v=f6bbb98c:2180:19)
    at index.ts:7:16
```

![image](https://github.com/user-attachments/assets/a2b4a959-985c-4d7a-b6ab-3a1bcd9c2725)
子路由的 `name` 属性与父路由的 `name` 相同，为什么在我的电脑就会报错

**Comment by YunaiV** [comment]
vue router 使用 4.4.9 版本，即可。
