### ISSUE TITLE
windows系统，master分支，pnpm i 安装完成之后，npm run front运行报错

### ISSUE THREAD

**Issue by threethieves** [yudaocode/yudao-ui-admin-vue3#12]
X [ERROR] Failed to resolve entry for package "ids". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-pre-bundle]

    node_modules/.pnpm/esbuild@0.18.13/node_modules/esbuild/lib/main.js:1370:21:
      1370 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28684:11)
    at resolvePackageEntry (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28681:5)
    at tryNodeResolve (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28415:20)
    at Context.resolveId (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28176:28)
    at Object.resolveId (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:44116:64)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:65707:21
    at async file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:39865:34
    at async requestCallbacks.on-resolve (D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:1370:22)
    at async handleRequest (D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:729:13)

  This error came from the "onResolve" callback registered here:

    node_modules/.pnpm/esbuild@0.18.13/node_modules/esbuild/lib/main.js:1289:20:
      1289 │       let promise = setup({
           ╵                     ^

    at setup (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:39845:19)
    at handlePlugins (D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:1289:21)
    at buildOrContextImpl (D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:978:5)
    at Object.buildOrContext (D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:786:5)
    at D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:2182:68
    at new Promise (<anonymous>)
    at Object.context (D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:2182:27)
    at Object.context (D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:2022:58)
    at prepareEsbuildOptimizerRun (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:45859:35)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/.pnpm/registry.npmmirror.com+bpmn-js@8.9.0/node_modules/bpmn-js/lib/draw/BpmnRenderer.js:58:16:
      58 │ import Ids from 'ids';
         ╵                 ~~~~~

X [ERROR] Failed to resolve entry for package "ids". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-pre-bundle]

    node_modules/.pnpm/esbuild@0.18.13/node_modules/esbuild/lib/main.js:1370:21:
      1370 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28684:11)
    at resolvePackageEntry (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28681:5)
    at tryNodeResolve (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28415:20)
    at Context.resolveId (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28176:28)
    at Object.resolveId (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:44116:64)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:65707:21
    at async file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:39865:34
    at async requestCallbacks.on-resolve (D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:1370:22)
    at async handleRequest (D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:729:13)

  This error came from the "onResolve" callback registered here:

    node_modules/.pnpm/esbuild@0.18.13/node_modules/esbuild/lib/main.js:1289:20:
      1289 │       let promise = setup({
           ╵                     ^

    at setup (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:39845:19)
    at handlePlugins (D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:1289:21)
    at buildOrContextImpl (D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:978:5)
    at Object.buildOrContext (D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:786:5)
    at D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:2182:68
    at new Promise (<anonymous>)
    at Object.context (D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:2182:27)
    at Object.context (D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:2022:58)
    at prepareEsbuildOptimizerRun (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:45859:35)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/.pnpm/registry.npmmirror.com+bpmn-js@8.9.0/node_modules/bpmn-js/lib/BaseModeler.js:3:16:    
      3 │ import Ids from 'ids';
        ╵                 ~~~~~

D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:1646
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 2 errors:
node_modules/.pnpm/esbuild@0.18.13/node_modules/esbuild/lib/main.js:1370:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "ids". The package may have incorrect main/module/exports specified 
in its package.json.
node_modules/.pnpm/esbuild@0.18.13/node_modules/esbuild/lib/main.js:1370:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "ids". The package may have incorrect main/module/exports specified 
in its package.json.
    at failureErrorWithLog (D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:1646:15)
    at D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:1058:25
    at D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:1522:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errors: [
    {
      detail: Error: Failed to resolve entry for package "ids". The package may have incorrect main/module/exports specified in its package.json.
          at packageEntryFailure (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28684:11)
          at resolvePackageEntry (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28681:5)
          at tryNodeResolve (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28415:20)
          at Context.resolveId (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28176:28)
          at Object.resolveId (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:44116:64)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:65707:21
          at async file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:39865:34
          at async requestCallbacks.on-resolve (D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:1370:22)
          at async handleRequest (D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:729:13),
      id: '',
      location: {
        column: 21,
        file: 'node_modules/.pnpm/esbuild@0.18.13/node_modules/esbuild/lib/main.js',
        length: 0,
        line: 1370,
        lineText: '        let result = await callback({\n' +
          '    at packageEntryFailure (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28684:11)\n' +          '    at resolvePackageEntry (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28681:5)\n' + 
          '    at tryNodeResolve (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28415:20)\n' +     
          '    at Context.resolveId (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28176:28)\n' +  
          '    at Object.resolveId (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:44116:64)\n' +   
          '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
          '    at async file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:65707:21\n' +
          '    at async file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:39865:34\n' +
          '    at async requestCallbacks.on-resolve (D:\\qihuang\\yudao-ui-admin-vue3\\node_modules\\.pnpm\\esbuild@0.18.13\\node_modules\\esbuild\\lib\\main.js:1370:22)\n' +
          '    at async handleRequest (D:\\qihuang\\yudao-ui-admin-vue3\\node_modules\\.pnpm\\esbuild@0.18.13\\node_modules\\esbuild\\lib\\main.js:729:13)',
        namespace: 'file',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 20,
            file: 'node_modules/.pnpm/esbuild@0.18.13/node_modules/esbuild/lib/main.js',
            length: 0,
            line: 1289,
            lineText: '      let promise = setup({\n' +
              '    at setup (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:39845:19)\n' +
              '    at handlePlugins (D:\\qihuang\\yudao-ui-admin-vue3\\node_modules\\.pnpm\\esbuild@0.18.13\\node_modules\\esbuild\\lib\\main.js:1289:21)\n' +
              '    at buildOrContextImpl (D:\\qihuang\\yudao-ui-admin-vue3\\node_modules\\.pnpm\\esbuild@0.18.13\\node_modules\\esbuild\\lib\\main.js:978:5)\n' +
              '    at Object.buildOrContext (D:\\qihuang\\yudao-ui-admin-vue3\\node_modules\\.pnpm\\esbuild@0.18.13\\node_modules\\esbuild\\lib\\main.js:786:5)\n' +
              '    at D:\\qihuang\\yudao-ui-admin-vue3\\node_modules\\.pnpm\\esbuild@0.18.13\\node_modules\\esbuild\\lib\\main.js:2182:68\n' +
              '    at new Promise (<anonymous>)\n' +
              '    at Object.context (D:\\qihuang\\yudao-ui-admin-vue3\\node_modules\\.pnpm\\esbuild@0.18.13\\node_modules\\esbuild\\lib\\main.js:2182:27)\n' +
              '    at Object.context (D:\\qihuang\\yudao-ui-admin-vue3\\node_modules\\.pnpm\\esbuild@0.18.13\\node_modules\\esbuild\\lib\\main.js:2022:58)\n' +
              '    at prepareEsbuildOptimizerRun (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:45859:35)',
            namespace: 'file',
            suggestion: ''
          },
          text: 'This error came from the "onResolve" callback registered here:'
        },
        {
          location: {
            column: 16,
            file: 'node_modules/.pnpm/registry.npmmirror.com+bpmn-js@8.9.0/node_modules/bpmn-js/lib/draw/BpmnRenderer.js',
            length: 5,
            line: 58,
            lineText: "import Ids from 'ids';",
            namespace: '',
            suggestion: ''
          },
          text: 'The plugin "vite:dep-pre-bundle" was triggered by this import'
        }
      ],
      pluginName: 'vite:dep-pre-bundle',
      text: 'Failed to resolve entry for package "ids". The package may have incorrect main/module/exports specified in its package.json.'
    },
    {
      detail: Error: Failed to resolve entry for package "ids". The package may have incorrect main/module/exports specified in its package.json.
          at packageEntryFailure (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28684:11)
          at resolvePackageEntry (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28681:5)
          at tryNodeResolve (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28415:20)
          at Context.resolveId (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28176:28)
          at Object.resolveId (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:44116:64)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:65707:21
          at async file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:39865:34
          at async requestCallbacks.on-resolve (D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:1370:22)
          at async handleRequest (D:\qihuang\yudao-ui-admin-vue3\node_modules\.pnpm\esbuild@0.18.13\node_modules\esbuild\lib\main.js:729:13),
      id: '',
      location: {
        column: 21,
        file: 'node_modules/.pnpm/esbuild@0.18.13/node_modules/esbuild/lib/main.js',
        length: 0,
        line: 1370,
        lineText: '        let result = await callback({\n' +
          '    at packageEntryFailure (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28684:11)\n' +          '    at resolvePackageEntry (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28681:5)\n' + 
          '    at tryNodeResolve (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28415:20)\n' +     
          '    at Context.resolveId (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28176:28)\n' +  
          '    at Object.resolveId (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:44116:64)\n' +   
          '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
          '    at async file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:65707:21\n' +
          '    at async file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:39865:34\n' +
          '    at async requestCallbacks.on-resolve (D:\\qihuang\\yudao-ui-admin-vue3\\node_modules\\.pnpm\\esbuild@0.18.13\\node_modules\\esbuild\\lib\\main.js:1370:22)\n' +
          '    at async handleRequest (D:\\qihuang\\yudao-ui-admin-vue3\\node_modules\\.pnpm\\esbuild@0.18.13\\node_modules\\esbuild\\lib\\main.js:729:13)',
        namespace: 'file',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 20,
            file: 'node_modules/.pnpm/esbuild@0.18.13/node_modules/esbuild/lib/main.js',
            length: 0,
            line: 1289,
            lineText: '      let promise = setup({\n' +
              '    at setup (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:39845:19)\n' +
              '    at handlePlugins (D:\\qihuang\\yudao-ui-admin-vue3\\node_modules\\.pnpm\\esbuild@0.18.13\\node_modules\\esbuild\\lib\\main.js:1289:21)\n' +
              '    at buildOrContextImpl (D:\\qihuang\\yudao-ui-admin-vue3\\node_modules\\.pnpm\\esbuild@0.18.13\\node_modules\\esbuild\\lib\\main.js:978:5)\n' +
              '    at Object.buildOrContext (D:\\qihuang\\yudao-ui-admin-vue3\\node_modules\\.pnpm\\esbuild@0.18.13\\node_modules\\esbuild\\lib\\main.js:786:5)\n' +
              '    at D:\\qihuang\\yudao-ui-admin-vue3\\node_modules\\.pnpm\\esbuild@0.18.13\\node_modules\\esbuild\\lib\\main.js:2182:68\n' +
              '    at new Promise (<anonymous>)\n' +
              '    at Object.context (D:\\qihuang\\yudao-ui-admin-vue3\\node_modules\\.pnpm\\esbuild@0.18.13\\node_modules\\esbuild\\lib\\main.js:2182:27)\n' +
              '    at Object.context (D:\\qihuang\\yudao-ui-admin-vue3\\node_modules\\.pnpm\\esbuild@0.18.13\\node_modules\\esbuild\\lib\\main.js:2022:58)\n' +
              '    at prepareEsbuildOptimizerRun (file:///D:/qihuang/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.4.2_@types+node@20.4.2_sass@1.63.6_terser@5.18.2/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:45859:35)',
            namespace: 'file',
            suggestion: ''
          },
          text: 'This error came from the "onResolve" callback registered here:'
        },
        {
          location: {
            column: 16,
            file: 'node_modules/.pnpm/registry.npmmirror.com+bpmn-js@8.9.0/node_modules/bpmn-js/lib/BaseModeler.js',
            length: 5,
            line: 3,
            lineText: "import Ids from 'ids';",
            namespace: '',
            suggestion: ''
          },
          text: 'The plugin "vite:dep-pre-bundle" was triggered by this import'
        }
      ],
      pluginName: 'vite:dep-pre-bundle',
      text: 'Failed to resolve entry for package "ids". The package may have incorrect main/module/exports specified in its package.json.'
    }
  ],
  warnings: []
}
 ELIFECYCLE  Command failed with exit code 1.

**Comment by YunaiV** [comment]
node 版本可能太低了，建议使用 16+
