### ISSUE TITLE
构建报错

### ISSUE THREAD

**Issue by khalidzk** [yudaocode/yudao-ui-admin-vue3#26]
版本v2.0.0
node版本：v16.20.2、v18.12、v20.5.0、v20.11.1，这几个版本都试过
pnpm版本：8.15.3
构建命令：npm run build:test
问题1：
Build failed. Please check the error message

error during build:
Error: Could not load /opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/src/views/crm/contract/components/BPMLModel.vue (imported by src/views/crm/contract/oa/ContractDetail/index.vue?vue&type=script&setup=true&lang.ts): ENOENT: no such file or directory, open '/opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/src/views/crm/contract/components/BPMLModel.vue'
 ELIFECYCLE  Command failed with exit code 1.

将src/views/crm/contract/oa/ContractDetail/index.vue文件中关于BPMLModel相关的代码注释后报问题2

问题2：
closeSeckillActivity的注释后没报了
后续还是一直报错"statSync" is not exported by "__vite-browser-external", imported by "node_modules/.pnpm/pkg-types@1.0.3/node_modules/pkg-types/dist/index.mjs".

详细如下：
> yudao-ui-admin-vue3@2.0.0-snapshot build:test
> node --max_old_space_size=8192 ./node_modules/vite/bin/vite.js build --mode test

src/views/mall/promotion/bargain/activity/index.vue?vue&type=script&setup=true&lang.ts (71:4) "closeSeckillActivity" is not exported by "src/api/mall/promotion/bargain/bargainActivity.ts", imported by "src/views/mall/promotion/bargain/activity/index.vue?vue&type=script&setup=true&lang.ts".

Build failed. Please check the error message

error during build:
RollupError: "statSync" is not exported by "__vite-browser-external", imported by "node_modules/.pnpm/pkg-types@1.0.3/node_modules/pkg-types/dist/index.mjs".
    at error (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Module.error (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
    at Module.traceVariable (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:14175:29)
    at ModuleScope.findVariable (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:12615:39)
    at ReturnValueScope.findVariable (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at ChildScope.findVariable (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at BlockScope.findVariable (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at Identifier.bind (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:8319:40)
    at CallExpression.bind (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
    at CallExpression.bind (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:9890:15)
    at MemberExpression.bind (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
    at MemberExpression.bind (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:9554:19)
    at CallExpression.bind (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
    at CallExpression.bind (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:9890:15)
    at IfStatement.bind (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
    at BlockStatement.bind (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
    at TryStatement.bind (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
    at BlockStatement.bind (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
    at ArrowFunctionExpression.bind (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
    at Property.bind (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
    at ObjectExpression.bind (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
    at VariableDeclarator.bind (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
    at VariableDeclaration.bind (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
    at Program.bind (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
    at Module.bindReferences (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:13741:18)
    at Graph.sortModules (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25853:20)
    at Graph.build (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25737:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:26706:13
    at async catchUnfinishedHookActions (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25910:16)
    at async rollupInternal (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:26701:5)
    at async build (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.5.0_@types+node@20.11.19_sass@1.71.0_terser@5.27.1/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48079:18)
    at async CAC.<anonymous> (file:///opt/gitWorkSpace/khalid/gitee/yudao-ui-admin-vue3/node_modules/.pnpm/vite@4.5.0_@types+node@20.11.19_sass@1.71.0_terser@5.27.1/node_modules/vite/dist/node/cli.js:842:9)

**Comment by khalidzk** [comment]
从v2.0.0版本切换master后已好
